# Generated by Django 5.1.3 on 2024-11-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=50)),
                ('date_of_joining', models.DateField()),
                ('photo_file_name', models.CharField(max_length=50)),
            ],
        ),
    ]
